# Webservice-Konfiguration
server:
  # Port des Tomcats
  port: 8081
  # Hostname/IP-Adresse des Hosts
  address: localhost
# Management-Endpoints
management:
  # Port, auf dem die Management-Schnittstellen erreichbar sind
  port: 8093
  context-path: /

# Logfile des Services
logging:
  file: service.log
  level:
    com.amazonaws: WARN
    org.apache: WARN
    org.springframework: WARN
    de.zdf.service.corpustagprovider: DEBUG

###################################################
# Konfiguration fuer den Kinesis-Consumer
###################################################
kinesis:
  # AWS-Region, in der sich der gewuenschte Kinesis-Stream befindet
  awsRegion: eu-central-1

  initialPosition: all
  #initialPositionTimestamp: "2017-07-28T09:25:00.000+02:00"

  # AWS-AccessKey
  tagStreamAccessKey: AKIAJIQ6IVDW7VPCOJ5Q
  # AWS-SecretKey
  tagStreamSecretKey: 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
  # Name des Kinesis-Streams, der als Datenquelle verwendet werden soll
  tagStreamName: tag-data-stream-gzs4
  # Name der Stream Consumer Group
  # (Alle Instanzen einer Consumer Group werden automatisch über die Shards eines Streams geloadbalanced)
  tagStreamConsumerGroup: DEV-tag-stream-consumer-group # INT

###################################################
# Konfiguration fuer Redis
###################################################
redis:
  host: localhost
  port: 6379

########################################
# Konfiguration fuer den Elasticsearch-Zugriff
########################################
elasticsearch:
  protocol: https
  host: zdf-test-kznrea-15782.exozet.com
  port: 443
  basePath: "/elasticsearch"
  useAuthHeader: true
  isBearer: false
  authField: "Authorization"
  authToken: "Basic c25yOkhpZTlzaWV2"

similarity:
  tagProviders: corpus,googleLanguage
  minWeightDiff: 0.001
  maxIndicators: 25
  maxDocsPerTerm: 30
  maxTermsPerDoc: 15
