version: "3.3"

volumes:
  similarity-service-redis-DEV:

services:
  java:
    image: registry.exozet.com/zdf/similarity-service:latest
    ports:
      - "8081:8081"
    volumes:
      - "./application.yml:/usr/src/app/application.yml"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - similarity-service-redis-DEV:/data
