# Webservice-Konfiguration
server:
  # Port des Tomcats
  port: 8081
  # Hostname/IP-Adresse des Hosts
  address: localhost
# Management-Endpoints
management:
  # Port, auf dem die Management-Schnittstellen erreichbar sind
  port: 8093
  context-path: /

# Logfile des Services
logging:
  file: service.log
  level:
    com.amazonaws: WARN
    org.apache: WARN
    org.springframework: WARN
    de.zdf.service.corpustagprovider: DEBUG

###################################################
# Konfiguration fuer den Kinesis-Consumer
###################################################
kinesis:
  # AWS-Region, in der sich der gewuenschte Kinesis-Stream befindet
  awsRegion: eu-central-1

  # AWS-AccessKey
  tagStreamAccessKey: AKIAJRSQY76BWJHPTU5Q
  # AWS-SecretKey
  tagStreamSecretKey: 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
  # Name des Kinesis-Streams, der als Datenquelle verwendet werden soll
  tagStreamName: tag-data-stream-PRODUCTION


redis:
  host: similarity-service-redis-master
  port: 6379

########################################
# Konfiguration fuer den Elasticsearch-Zugriff
########################################
elasticsearch:
  protocol: https
  host: "es-3po-elsec.zdf.de"
  port: 443
  useAuthHeader: false
  isBearer: false
  # authField: "Authorization"
  # echo "aws_elsac:aimieF7R" | base64
  # authToken: "Basic YXdzX2Vsc2FjOmFpbWllRjdSCg"
  username: aws_elsac
  password: aimieF7R


similarity:
  tagProviders: corpus,googleLanguage
  minWeightDiff: 0.001
  maxIndicators: 25
  maxDocsPerTerm: 30
  maxTermsPerDoc: 15