# Webservice-Konfiguration
server:
  # Port des Tomcats
  port: 8081
  # Hostname/IP-Adresse des Hosts
  address: localhost
# Management-Endpoints
management:
  # Port, auf dem die Management-Schnittstellen erreichbar sind
  port: 8093
  context-path: /

# Logfile des Services
logging:
  file: service.log
  level:
    com.amazonaws: WARN
    org.apache: WARN
    org.springframework: WARN
    de.zdf.service.corpustagprovider: DEBUG

###################################################
# Konfiguration fuer den Kinesis-Consumer
###################################################
kinesis:
  # AWS-Region, in der sich der gewuenschte Kinesis-Stream befindet
  awsRegion: eu-central-1

  # AWS-AccessKey
  tagStreamAccessKey: AKIAIWNK2SIPAEEJMDTQ
  # AWS-SecretKey
  tagStreamSecretKey: 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
  # Name des Kinesis-Streams, der als Datenquelle verwendet werden soll
  tagStreamName: tag-data-stream-INTEGRATION

redis:
  host: similarity-service-redis-master
  port: 6379

########################################
# Konfiguration fuer den Elasticsearch-Zugriff
########################################
elasticsearch:
  protocol: https
  host: es-3it-elsec.zdf.de
  port: 443
  useAuthHeader: false
  isBearer: false
  # authField: "Authorization"
  # echo "aws_elsac:aimieF7R" | base64
  # authToken: "Basic YXdzX2Vsc2FjOmFpbWllRjdSCg"
  username: aws_elsac
  password: aimieF7R